name: Build and Publish Godot Game

on:
  push:
    branches: [main]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  export-html5:
    name: Export to HTML5 and Deploy to GitHub Pages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Godot
        uses: chickensoft-games/setup-godot@v1
        with:
          version: 4.4.1  # or 3.5.2 depending on your project
          export-templates: true
          use-mono: false

      - name: Create export directory
        run: mkdir -p build/web

      - name: Export HTML5 game
        run: godot --headless --export-release "Web"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
